# ========================
# 🛠️ ОБЩИЕ НАСТРОЙКИ
# ========================
general:
  project_name: "Vitalik"
  version: "1.0"
  random_seed: 42
  log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  save_model_path: "./models/vitalik_model.pth"
  save_meta_model_path: "./models/vitalik_meta.pth"
  training_log_path: "./logs/training.log"
  agent_actions_log_path: "./logs/agent_actions.log"
  prediction_log_path: "./data/predictions.log"

# ========================
# 📊 ПАРАМЕТРЫ ОБУЧЕНИЯ
# ========================
training:
  epochs: 1000           # Количество эпох обучения
  batch_size: 32         # Размер батча
  learning_rate: 0.001   # Скорость обучения
  gamma: 0.99            # Коэффициент дисконтирования для RL
  clip_grad_norm: 0.5    # Ограничение градиента для стабильности
  target_update_freq: 10 # Частота обновления целевой сети

# ========================
# 🤖 ПАРАМЕТРЫ МОДЕЛИ
# ========================
model:
  type: "Actor-Critic"   # Тип модели (Actor-Critic, PPO, SAC)
  hidden_size: 128       # Размер скрытого слоя нейросети
  num_layers: 2          # Количество LSTM-слоев
  dropout: 0.1           # Вероятность dropout для регуляризации

# ========================
# ⚙️ ПАРАМЕТРЫ MAML (META-LEARNING)
# ========================
maml:
  inner_learning_rate: 0.01 # Внутренняя скорость обучения
  outer_learning_rate: 0.001 # Внешняя скорость обучения
  adaptation_steps: 5       # Количество шагов адаптации

# ========================
# 📡 НАСТРОЙКИ ВЗАИМОДЕЙСТВИЯ С АГЕНТОМ
# ========================
agent:
  exploration_rate: 0.1    # Вероятность случайного действия (Exploration)
  exploration_decay: 0.99  # Скорость уменьшения exploration_rate
  max_memory_size: 10000   # Максимальный размер памяти для Replay Buffer
  action_repeat: 1         # Количество повторений одного действия

# ========================
# 🗂️ ПУТИ К ДАННЫМ
# ========================
paths:
  training_data: "./data/training_data.pkl"
  predictions_log: "./data/predictions.log"

# ========================
# 📊 МЕТРИКИ
# ========================
metrics:
  log_interval: 10      # Интервал логирования метрик
  eval_interval: 50     # Интервал оценки агента на валидации
  best_model_metric: "loss" # Метрика для сохранения лучшей модели (accuracy, loss)

# ========================
# 📝 РЕЖИМ РАБОТЫ
# ========================
mode:
  manual_input: true   # Включить ручной ввод данных
  real_time_training: false # Включить обучение в реальном времени
